export const INIT_GAME = 'INIT_GAME';
export const INIT_GAME_ACTION = 'INIT_GAME_ACTION';
export const CLICK_TILE_ACTION = 'CLICK_TILE_ACTION';
export const CLICK_TILE = 'CLICK_TILE';
export const AVAILABLE_MOVES = 'AVAILABLE_MOVES';
